account/urls.py
from os import name
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = [
    path("login", views.login, name='login'),  # 用户登录
    path('logout', views.logout, name='logout'),  # 用户退出
    path("del_user", views.del_user, name="del_user"),  # 用户删除
    path("edit_user/<user_id>", views.edit_user, name="edit_user"),   # 用户修改
    path("error_404", views.error_404, name="error_404"),   # 错误页面
    path("", views.account, name='account'),  # 后台管理之用户注册
]

business/urls.py
from os import name
from django.urls import path
from business.views import process_control, dp

app_name = 'business'

urlpatterns = [
    path("vehicle_info", process_control.vehicle_info, name="vehicle_info"),  # 信息录入
    path('spectaculars', process_control.spectaculars, name="spectaculars"),  # 动态看板
    path("vehicle_status_edit", process_control.vehicle_status_edit, name="vehicle_status_edit"),  # 车辆状态操作
    path("vehicle_road_status_edit", process_control.vehicle_road_status_edit, name="vehicle_road_status_edit"),  # 路试
    path("vehicle_care_of", process_control.vehicle_care_of, name="vehicle_care_of"),   # 车辆转接操作
    path("add_dispatch_team", process_control.add_dispatch_team, name="add_dispatch_team"),   # 增项派工
    path('unfinished', process_control.unfinished, name='unfinished'),   # 未完成在场车辆
    path("vehicle_info_edit", process_control.vehicle_info_edit, name="vehicle_info_edit"),   # 车辆信息修改
    path("team_vehicle_info_view", process_control.team_vehicle_info_view, name="team_vehicle_info_view"),  # 班组车辆信息
    path('data_report', dp.data_report, name="data_report"),  # 数据报表
    path("", process_control.index, name='index'),   # 首页
]

wms/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include('account.urls', namespace='account')), 
    path("", include('business.urls', namespace='business')), 
]

account/models.py
from django.db import models


# 用户表
class UserProfile(models.Model):
    username = models.CharField(max_length=32, unique=True, verbose_name="用户名")
    password = models.CharField(max_length=32, verbose_name='密码')
    mobile_phone = models.CharField(max_length=32, verbose_name='手机号', unique=True)
    role = models.ForeignKey('Role', on_delete=models.CASCADE, verbose_name='角色')
    team = models.ForeignKey('Team', on_delete=models.CASCADE, verbose_name='组别')

    def __str__(self):
        return self.username
    
    class Meta:
        verbose_name = "用户表"
        verbose_name_plural = verbose_name


# 班组表
class Team(models.Model):
    caption = models.CharField(max_length=32, verbose_name='班组')

    def __str__(self):
        return self.caption

    class Meta:
        verbose_name = "班组表"
        verbose_name_plural = verbose_name


# 角色表
class Role(models.Model):
    caption = models.CharField(max_length=32, verbose_name='角色')
    create_time = models.DateTimeField(auto_now=True, verbose_name='创建时间')
    last_time = models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间')
 
    def __str__(self):
        return self.caption
    
    class Meta:
        verbose_name = "角色表"
        verbose_name_plural = verbose_name


# 菜单表（URL）
class Menu(models.Model):
    title = models.CharField(max_length=32, verbose_name='菜单名')
    url = models.CharField(max_length=60, verbose_name='URL')

    def __str__(self):
        return "%s - %s" % (self.title, self.url)

    class Meta:
        verbose_name = "菜单表"
        verbose_name_plural = verbose_name


# 权限表(角色绑定菜单URL)
class Permission(models.Model):
    role = models.ForeignKey('Role', on_delete=models.CASCADE, verbose_name='角色')
    menu_title = models.ForeignKey('Menu', on_delete=models.CASCADE, verbose_name='菜单')

    def __str__(self):
        return "%s - %s" % (self.role, self.menu_title)

    class Meta:
        verbose_name = "权限表"
        verbose_name_plural = verbose_name

account/forms/account_forms.py
from django import forms
from django.core.validators import RegexValidator  # 调用进行正则校验
from django.core.exceptions import ValidationError  # 抛出错误信息
from account import models
from utils.md5 import encrypt


class RegisterForm(forms.ModelForm):
    """用户注册表单"""
    mobile_phone = forms.CharField(label='手机号', validators=[RegexValidator(
        r"^[1](([3][0-9])|([4][5-9])|([5][0-3,5-9])|([6][5,6])|([7][0-8])|([8][0-9])|([9][1,8,9]))[0-9]{8}$",
        '手机号格式错误')], error_messages={'unique': '手机号已经注册'})
    password = forms.CharField(label='密码', min_length=6, max_length=16, widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='重复密码', min_length=6, max_length=16, widget=forms.PasswordInput)

    class Meta:
        model = models.UserProfile
        fields = ['username', 'mobile_phone', 'role', 'team', 'password', 'confirm_password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off',
            })

    # 用户名验证
    def clean_username(self):
        username = self.cleaned_data['username']

        if not username:
            raise ValidationError('用户名不能为空！')
        return username

    # 手机号验证
    def clean_mobile_phone(self):
        mobile_phone = self.cleaned_data['mobile_phone']
        exists = models.UserProfile.objects.filter(mobile_phone=mobile_phone).exists()

        if not mobile_phone:
            raise ValidationError('手机号不能为空！')
        return mobile_phone

    # 角色验证
    def clean_role(self):
        role = self.cleaned_data.get('role')
        if role == "":
            raise ValidationError('用户角色不能为空！')
        return role
    
    # 组别验证
    def clean_team(self):
        team = self.cleaned_data.get('team')
        if team == "":
            raise ValidationError('用户组别不能为空!')
        return team

    # 加密密码 (如果不加密，存储在数据库中的密码是明文的，容易撞库，泄露密码。我们使用md5加密处理)
    def clean_password(self):
        pwd = self.cleaned_data['password']
        return encrypt(pwd)

    # 密码验证
    def clean_confirm_password(self):
        pwd = self.cleaned_data['password']
        confirm_password = encrypt(self.cleaned_data.get('confirm_password'))

        if pwd != confirm_password:
            raise ValidationError('两次密码输入不一致')
        return confirm_password

account/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .forms.account_forms import RegisterForm
from account.models import UserProfile
from utils.md5 import encrypt
from utils.login_auth import admin_permission  # 自定义登录认证组件


@admin_permission
def account(request):
    """
    用户管理界面之用户注册处理
    """
    context = {}
    if request.method == "GET":
        form = RegisterForm()
        user_lis = UserProfile.objects.all()
        context['user_lis'] = user_lis
        context['form'] = form
        return render(request, 'account.html', context)

    form = RegisterForm(data=request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True, 'data': '/index'})  # 返回给前端json数据
    return JsonResponse({'status': False, 'errors': form.errors})  # 验证失败返回给失败的信息


def login(request):
    """
    用户登录处理
    """
    if request.method == "GET":
        return render(request, 'login.html')
    else:
        mobile_phone = request.POST.get('mobile_phone', '')
        pwd = encrypt(request.POST.get('password', ''))
        if mobile_phone == "" or pwd == "":
            return JsonResponse({'status': False, 'errors': "手机号或密码不能为空"})

        user_obj = UserProfile.objects.filter(mobile_phone=mobile_phone, password=pwd).first()
        if user_obj:
            request.session['user_id'] = user_obj.id
            request.session.set_expiry(60 * 60 * 24 * 7)  # 设置存储的过期时间7天
            return JsonResponse({'status': True})
        else:
            return JsonResponse({'status': False, 'errors': "用户名或者密码错误"})


def logout(request):
    """
    退出登录
    """
    request.session.flush()
    return redirect('account:login')


@admin_permission
def del_user(request):
    """用户删除"""
    user_name = request.GET.get('user_name')
    UserProfile.objects.filter(username=user_name).delete()
    return JsonResponse({'status': True})


@admin_permission
def edit_user(request, user_id):
    """用户修改"""
    user_obj = UserProfile.objects.filter(id=user_id).first()
    if request.method == "GET":
        form = RegisterForm(instance=user_obj)
        return render(request, 'edit_user.html', {'form': form})

    form = RegisterForm(data=request.POST, instance=user_obj)
    if form.is_valid():
        form.save()
        return redirect("account:account")
    else:
        return render(request, 'edit_user.html', {"form": form})   # 验证失败返回给失败的信息


def error_404(request):
    """错误页面"""
    return render(request, 'admin_404.html')

templates/account.html
{% extends 'base.html' %}
{% block admin %}"active"{% endblock %}
{% block css %}
    <style>
        .error-msg {
            font-size: 8px;
            color: red;
            position: absolute;
        }

        .register-success {
            font-size: 10px;
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}
{% block heading %}后台管理{% endblock %}
{% block main %}
    <!-- start: PAGE CONTENT -->
    <div class="row">
        <div class="col-sm-12">
            <div class="tabbable">
                <ul class="nav nav-tabs tab-padding tab-space-3 tab-blue" id="myTab4">
                    <li>
                        <a data-toggle="tab" href="#panel_edit_account">
                            新 增 用 户
                        </a>
                    </li>
                    <li class="active" id='user-list'>
                        <a data-toggle="tab" href="#panel_projects">
                            用 户 列 表
                        </a>
                    </li>
                </ul>
                <div class="tab-content">
                    <!-- 新增用户 -->
                    <div id="panel_edit_account" class="tab-pane fade">
                        <div class="row">
                            <div class="col-md-12">
                                <p class='register-success'></p>
                                <hr>
                            </div>
                            <div class="panel-body">
                                <form class="smart-wizard form-horizontal" id="registerForm">
                                    {% csrf_token %}
                                    <div id="wizard" class="swMain">
                                        <div class="progress progress-xs transparent-black no-radius active">
                                            <div aria-valuemax="100" aria-valuemin="0" role="progressbar"
                                                 class="progress-bar partition-green step-bar">
                                            </div>
                                        </div>
                                        <div id="step-1">
                                            {% for file in form %}
                                                <div class="form-group" id='register-field'>
                                                    <label class="col-sm-3 control-label">
                                                        {{ file.label }} <span class="symbol required"></span>
                                                    </label>
                                                    <div class="col-sm-7">
                                                        {{ file }}
                                                        <span class='error-msg'></span>
                                                    </div>
                                                </div>

                                            {% endfor %}
                                            <div class="form-group">
                                                <div class="col-sm-2 col-sm-offset-8">
                                                    <button class="btn btn-blue" id='btnSubmit' type='button'>
                                                        信 息 提 交 <i class="fa fa-arrow-circle-right"></i>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div id="panel_projects" class="tab-pane fade in active">
                        <table class="table table-striped table-bordered table-hover" id="projects">
                            <thead>
                            <tr>
                                <th class="center">ID</th>
                                <th class="center">用户姓名</th>
                                <th class="center">手机号</th>
                                <th class="hidden-xs center">职位</th>
                                <th class="hidden-xs center">班组</th>
                                <th class="hidden-xs center">修改信息</th>
                                <th class="hidden-xs center">删除用户</th>
                            </tr>
                            </thead>
                            <tbody class='tab-tr'>
                            {% for user in user_lis %}
                                <tr>
                                    <td class="center user-id">{{ user.id }}</td>
                                    <td class="center user-name">{{ user.username }}</td>
                                    <td class="center">{{ user.mobile_phone }}</td>
                                    <td class="hidden-xs center">{{ user.role }}</td>
                                    <td class="center hidden-xs">{{ user.team }}</td>
                                    <td class="center visible-md visible-lg hidden-sm hidden-xs edit-user">
                                        <a href="{% url 'account:edit_user' user.id %}"
                                           class="btn btn-light-blue tooltips" data-placement="top"
                                           data-original-title="修改"><i class="fa fa-edit"></i></a>
                                    </td>
                                    <td class="center visible-md visible-lg hidden-sm hidden-xs del-user">
                                        <a href="#" class="btn btn-red tooltips" data-placement="top"
                                           data-original-title="删除"><i class="fa fa-times fa fa-white"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end: PAGE CONTENT-->
{% endblock %}
{% block js %}
    <script>
        $(function () {
            /* 用户注册*/
            /* 1.每次点击清空错误信息；2.错误信息显示在对应输入框下方； 3.注册成功清空表单信息 ; 4.显示成功信息；*/
            $('#btnSubmit').on("click", function () {
                $('.error-msg').text("");
                $.ajax({
                    url: "{% url 'account:account' %}",
                    type: 'POST',
                    data: $('#registerForm').serialize(),
                    success: function (res) {
                        if (res.status) {
                            removeSuccess();
                            $('#registerForm')[0].reset();
                        } else {
                            $.each(res.errors, function (key, value) {
                                $('#id_' + key).next().text(value);
                            })
                        }
                    }
                })
            })
        })

        /*删除成功信息 5秒*/
        function removeSuccess() {
            $('.register-success').text('增员成功');
            setTimeout(function () {
                $('.register-success').text("");
            }, 5000)
        }

        /*点击用户列表tab，更新用户列表数据*/
        $('#user-list').on("click", function () {
            location.href = "/account/"
        })

        /* 动态删除用户 */
        $('.del-user').on('click', function () {
            let userName = $(this).siblings('.user-name').text();
            let t = confirm("确定要删除用户 > " + userName + " < 这个账号吗？");
            let that = $(this);
            if (t === true) {
                $.ajax({
                    url: "{% url 'account:del_user'%}",
                    type: 'GET',
                    data: {user_name: userName},
                    success: function (res) {
                        if (res.status) {
                            that.parent().remove();
                        }
                    }
                })
            }
        })
    </script>
{% endblock %}

templates/admin_404.html
{% load static %}
<!DOCTYPE html>
<!-- Template Name: Rapido - Responsive Admin Template build with Twitter Bootstrap 3.x Version: 1.3 Author: ClipTheme -->
<!--[if IE 8]><html class="ie8 no-js" lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9 no-js" lang="en"><![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
	<!--<![endif]-->
	<!-- start: HEAD -->
	<head>
		<title>BMW - 维修车辆管理平台</title>
		<!-- start: META -->
		<meta charset="utf-8" />
		<!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<meta content="" name="description" />
		<meta content="" name="author" />
		<!-- end: META -->
		<!-- start: MAIN CSS -->
		<link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles-responsive.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/animate.css/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/print.css' %}">
		<!-- end: MAIN CSS -->
		<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
		<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
		<link rel="shortcut icon" href="{% static 'images/logo.ico' %}" />
	</head>
	<!-- end: HEAD -->
	<!-- start: BODY -->
	<body class="error-full-page">
		<!-- start: PAGE -->
		<div class="container">
			<div class="row">
				<!-- start: 404 -->
				<div class="col-sm-12 page-error animated shake">
					<div class="error-number text-azure">
						404
					</div>
                    <br><br><br>
					<div class="error-details col-sm-6 col-sm-offset-3">
						<h2>您的账号暂无权限访问该页面！！</h2><br><br>
						<p>
							古之立大事者，不惟有超世之才，亦必有坚忍不拔之志. -- 陶行知
							<br><br>
							一个有坚强心志的人，财产可以被人掠夺，勇气却不会被人剥夺的. -- 雨果
							<br><br>
							在劳力上劳心，是一切发明之母。事事在劳力上劳心，变可得事物之真理。 -- 陶行知
							<br><br>
							<a href="{% url 'business:index' %}" class="btn btn-red btn-return">
								返 回 首 页
							</a>
							<br><br>
							你想知道人生哲理吗 ?
							<br><br>
							聪明的资质、内在的干劲、勤奋的工作态度和坚忍不拔的精神，这些是成功所需要的其他条件. -- 贝弗里奇
						</p>
					</div>
				</div>
				<!-- end: 404 -->
			</div>
		</div>
		<!-- end: PAGE -->
		<!-- start: MAIN JAVASCRIPTS -->
		<!--[if lt IE 9]>
        <script src='{% static 'plugins/respond.min.js' %}'></script>
<script src='{% static 'plugins/excanvas.min.js' %}'></script>
<script src='{% static 'plugins/jQuery/jquery-1.11.1.min.js' %}'></script>
		<![endif]-->
		<!--[if gte IE 9]><!-->
        <script src='{% static 'plugins/jQuery/jquery-2.1.1.min.js' %}'></script>
		<!--<![endif]-->
        <script src='{% static 'plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js' %}'></script>
        <script src='{% static 'plugins/bootstrap/js/bootstrap.min.js' %}'></script>
        <script src='{% static 'plugins/jquery-cookie/jquery.cookie.js' %}'></script>
        <script src='{% static 'plugins/TouchSwipe/jquery.touchSwipe.min.js' %}'></script>
        <script src='{% static 'js/main.js' %}'></script>
		<!-- end: MAIN JAVASCRIPTS -->
		<script>
			jQuery(document).ready(function() {
				Main.init();
			});
		</script>
	</body>
	<!-- end: BODY -->
</html>

templates/data_report.html
{% extends 'base.html' %}
{% block data %}"active"{% endblock %}
{% block  heading%}数据报表{% endblock %}
{% block main %}


{% endblock %}

templates/edit_user.html
{% extends 'base.html' %}
{% block admin %}"active"{% endblock %}
{% block css %}
    <style>
        .error-msg {
            font-size: 8px;
            color: red;
            position: absolute;
        }

        .register-success {
            font-size: 10px;
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}
{% block heading %}后台管理{% endblock %}
{% block main %}
    <!-- start: PAGE CONTENT -->
    <div class="row">
        <div class="col-sm-12">
            <div class="tabbable">
                <ul class="nav nav-tabs tab-padding tab-space-3 tab-blue" id="myTab4">
                    <li class="active">
                        <a data-toggle="tab" href="#panel_edit_account">
                            用 户 信 息 修 改
                        </a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div id="panel_edit_account" class="tab-pane fade in active">
                        <div class="row">
                            <div class="col-md-12">
                                <p class='register-success'></p>
                                <hr>
                            </div>
                            <div class="panel-body">
                                <form class="smart-wizard form-horizontal" method="post">
                                    {% csrf_token %}
                                    <div id="wizard" class="swMain">
                                        <div class="progress progress-xs transparent-black no-radius active">
                                            <div aria-valuemax="100" aria-valuemin="0" role="progressbar"
                                                 class="progress-bar partition-green step-bar">
                                            </div>
                                        </div>
                                        <div id="step-1">
                                            {% for file in form %}
                                                <div class="form-group" id='register-field'>
                                                    <label class="col-sm-3 control-label">
                                                        {{ file.label }} <span class="symbol required"></span>
                                                    </label>
                                                    <div class="col-sm-7">
                                                        {{ file }}
                                                        <span class='error-msg'>{{ file.errors.0 }}</span>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                            <div class="form-group">
                                                <div class="col-sm-2 col-sm-offset-8">
                                                    <button class="btn btn-blue" id='btnSubmit' type='submit'>
                                                        信 息 提 交 <i class="fa fa-arrow-circle-right"></i>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end: PAGE CONTENT-->
{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- start: HEAD -->
<head>
    <title>BMW - 机修车辆管理平台</title>
    <!-- start: META -->
    <meta charset="utf-8"/>
    <!--[if IE]>
    <meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1"/><![endif]-->
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!-- end: META -->
    <!-- start: MAIN CSS -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/animate.css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/iCheck/skins/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles-responsive.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/iCheck/skins/all.css' %}">
    <!-- end: MAIN CSS -->
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
</head>
<!-- end: HEAD -->
<!-- start: BODY -->
<body class="login">
<div class="row">
    <div class="main-login col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
        <div class="logo">
            <img src="{% static 'images/logo.png' %}">
        </div>
        <!-- start: LOGIN BOX -->
        <div class="box-login">
            <h3>BMW机修车辆管理平台</h3>
            <br>
            <form id="loginForm">
                {% csrf_token %}
                <fieldset>
                    <div class="form-group">
                        <span class="input-icon">
                            <input type="text" class="form-control" name="mobile_phone" placeholder="手机号码"
                                   autocomplete="off">
                            <i class="fa fa-user"></i>
                        </span>
                    </div>
                    <div class="form-group form-actions">
                        <span class="input-icon">
                            <input type="password" class="form-control password" name="password" placeholder="密码">
                            <i class="fa fa-lock"></i>
                            <a class="forgot" href="#">
                                忘记密码？
                            </a>
                        </span>
                    </div>
                    <div class="form-actions">
                        <label class="checkbox-inline" id="error-msg" style="color: red;"></label>
                        <button type="button" class="btn btn-green pull-right" id="loginSubmit">
                            登录 <i class="fa fa-arrow-circle-right"></i>
                        </button>
                    </div>
                </fieldset>
            </form>
            <!-- start: COPYRIGHT -->
            <div class="copyright">
                2020 &copy; SunBo Network Studio
            </div>
            <!-- end: COPYRIGHT -->
        </div>
        <!-- end: LOGIN BOX -->
        <!-- start: FORGOT BOX -->
        <div class="box-forgot">
            <h3>找回你的密码?</h3>
            <p>
                请输入您的手机号，通过短信验证来找回密码.
            </p>
            <form class="form-forgot">
                <div class="errorHandler alert alert-danger">
                    <i class="fa fa-remove-sign fa-meh-o"></i> 发短信太贵！发不起短信！找管理员去吧！
                     <i class="fa fa-mobile-phone"></i> 15053108622
                </div>
                <fieldset>
                    <div class="form-group">
{#                        <span class="input-icon">#}
{#                            <input type="email" class="form-control" name="email" placeholder="暂时没钱发短信，所以找管理员去吧！">#}
{#                            <i class="fa fa-envelope"></i> </span>#}
                    </div>
                    <div class="form-actions">
                        <a class="btn btn-light-grey go-back">
                            <i class="fa fa-chevron-circle-left"></i> 返 回 登 录
                        </a>
                        <button type="button" class="btn btn-green pull-right">
                            提交也没用 <i class="fa fa-arrow-circle-right"></i>
                        </button>
                    </div>
                </fieldset>
            </form>
            <!-- start: COPYRIGHT -->
            <div class="copyright">
                2020 &copy; SunBo Network Studio
            </div>
            <!-- end: COPYRIGHT -->
        </div>
        <!-- end: FORGOT BOX -->
    </div>
</div>
<!-- start: MAIN JAVASCRIPTS -->
<!--[if lt IE 9]>
		<script src="{% static 'plugins/respond.min.js'%}"></script>
<script src="{% static 'plugins/excanvas.min.js'%}"></script>
<script src="{% static 'plugins/jQuery/jquery-1.11.1.min.js'%}"></script>
		<![endif]-->
<!--[if gte IE 9]><!-->
<script src="{% static 'plugins/jQuery/jquery-2.1.1.min.js' %}"></script>
<!--<![endif]-->
<script src="{% static 'plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/iCheck/jquery.icheck.min.js' %}"></script>
<script src="{% static 'plugins/jquery.transit/jquery.transit.js' %}"></script>
<script src="{% static 'plugins/TouchSwipe/jquery.touchSwipe.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- end: MAIN JAVASCRIPTS -->
<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<script src="{% static 'plugins/jquery-validation/dist/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/login.js' %}"></script>
<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<script>
    jQuery(document).ready(function () {
        Main.init();
        Login.init();

        $('#loginSubmit').on('click', function () {
             $('#error-msg').empty();
            $.ajax({
                url: "{% url 'account:login' %}",
                type: "POST",
                data: $('#loginForm').serialize(),
                cache: false,
                success: function (res) {
                    if(res.status){
                        location.href = "/"
                    }else {
                        $('#error-msg').text(res.errors)
                    }
                }
            })
        })

    });
</script>
</body>
<!-- end: BODY -->
</html>